// ---------------------------------------------------------------------------
// The hospitality doctrine: the single knowledge base every AI generator is
// grounded in. It distills the operating principles behind world-class
// hospitality into rules the model can APPLY when it builds a training
// program, hiring guide, accountability checklist, or whole system.
//
// These are paraphrased operating principles, not quotations -- draw on them
// conceptually. Edit this one file to retrain every generator at once.
// ---------------------------------------------------------------------------

export const HOSPITALITY_DOCTRINE = `WORLD-CLASS HOSPITALITY DOCTRINE -- apply every principle below when you build anything:

1. Hospitality is not service. Service completes a task; hospitality creates a genuine human connection and a reason to come back. Always optimize for the connection, never just the task.

2. Sell reactions, not transactions. Every touchpoint should produce a specific, intended emotional reaction in the guest. A step that produces no reaction is dead weight -- name the reaction each behavior should create. Recognition and personalization outrank the transaction: a returning guest must never be treated like a stranger.

3. The visit ladder. Loyalty is built one visit at a time, and the third visit is the tipping point into "regular." Design and train deliberately to earn the very next visit -- flag first-time guests in the moment so the whole team converts them. Measure the payoff in real money: the revenue from a guest's 2nd, 3rd, and 4th visits is the retention program's actual ROI -- dollars you would not have if the first visit had been the last. Track the bill total at each visit so "repeat-visit revenue" is a real number, not an estimate, and so you can see which visit stage is worth the most. A loyalty program only compounds if the front of house actually works it every shift: ask every guest whether they're a member, sign up the ones who aren't, capture missing numbers, and check points/rewards so members feel seen -- make this a short, checkable FOH habit, because the biggest leak in most programs is simply that the floor never asks.

4. Standards must be qualifiable, quantifiable, and verifiable -- and are worthless unless someone inspects them. Never write a vague value ("be welcoming"); convert it into a specific, observable behavior with a number or a trigger where possible ("greet within 30 seconds," "one named recommendation per course"). If a manager can't watch for it, rewrite it.

5. Consistency comes from small daily reps, not one-time onboarding. Favor short, repeatable drills; certify skills live (a manager watches the behavior and signs off); and assume constant, never-ending improvement rather than a finished program. Verify knowledge too, not just behavior: a short, fair test with a clear passing bar (e.g. 80%) proves someone actually learned the food, the bar, or a new menu -- and a failed test is a coaching trigger, not a punishment. Teach first, then quiz, when the material is new (a limited-time offer or a rotating menu); keep straight knowledge checks brief and objective. Because hospitality can't be taught once and considered done, make the best training RECURRING: a short monthly "day one" refresher that re-assigns itself as a fresh attempt keeps the standard alive far better than a one-time onboarding course. Make guest-experience hospitality the baseline every role recurs on, and layer short role-specific refreshers on top where the craft demands it -- a bartender's drink specs and pours, a line cook's plating and allergen handling -- so every position sharpens both the shared standard and its own skills.

6. Guided influence has a structure -- teach it, don't leave it to instinct: genuinely identify with the guest first, give a concrete reason, name the likely objection before they raise it, contrast the upside against the cost, then ask for the action. This same structure powers both suggestive selling and guest recovery.

7. Surprise and delight. Unplanned, unexpected gestures (a remembered name, a comped taste, a small upgrade) build loyalty faster than any predictable perk. Leave room for them.

8. The physical environment is a lever on reactions and spend -- sight lines and flow, lighting, music tempo and volume, comfort, plating, and the cleanliness of glassware and restrooms guests judge you by within seconds. This is every role's job (Host, Manager, Chef, and Bartender included), not only front-of-house.

9. People are driven by different motivators -- financial security, pride in their craft, recognition and status, or fear of failure. Read the person and coach or hire to what actually drives them. When correcting, praise in public and correct in private: open with a specific compliment, give a specific fix, and leave them wanting to do better.

10. Every role owns the guest experience, from Host to Chef to Manager. Guest experience is embedded into every role's standards, never bolted on as a separate topic.

11. Map the guest experience as an ordered journey of distinct moments, from the moment of arrival to the goodbye and the ask for a review. Each moment is a designed touchpoint with its own standard, not an accident. Treat the sequence as the backbone the team trains on and is inspected against.

12. Per-moment coaching structure. For each journey moment, define: why it matters, the common mistake that quietly kills it, the non-negotiable observable behavior, and a concrete example of what to say or do. Aim for roughly 80% repeatable system and 20% personal warmth -- scripted enough to be consistent, human enough to feel real.

13. Specific high-leverage moments to get right: acknowledge a guest within the first seconds of arrival, before they reach anyone; at every hand-off between team members, add a genuine moment (a recommendation, a compliment of a teammate by name) instead of a flat "someone will be with you"; early on, learn whether a guest is new or returning and branch the experience accordingly (educate the newcomer, honor the regular); recommend by naming the item, why it's genuinely worth it, and a reason to choose it now; when you check back, reference the exact dish or drink you recommended and speak to each guest, not the table, quickly rather than "when convenient"; end as strongly as you began, because the last moment is what a guest remembers and repeats.

14. Menu and product knowledge is revenue. The menu is ONE shared thing, learned in two layers. Everyone who sells an item -- servers for food, the whole floor for drinks -- must know it cold: ingredients, allergens, and why it is good, so they sell more without pressuring anyone. The people who MAKE it need that same knowledge PLUS how to make it: the kitchen for food, the bartender for cocktails. So the RECIPE -- an ordered, step-by-step "how to make it" with a real photo on each step -- is the maker's layer on a shared dish or drink, not a separate menu; a photographed, numbered recipe is the single best guarantee of plating, prep, and pour consistency, and it doubles as the source material for a knowledge test that verifies the maker actually knows the build. Build short pre-shift tastings and quick knowledge checks; treat mastery as a standard, not a bonus. Limited-time offers are a knowledge moment too -- when a special is only here this month, the team should know it best and sell it hardest while it lasts.

15. Earn the review, then ask. Only ask for a rating after delivering an experience genuinely worth reviewing, make the ask personal rather than transactional, and time it to the natural end of the visit. A great experience unasked-for is a review left on the table.

16. Purpose, pride, and a people-first culture -- the retention engine. The brands with the best guest experience AND the lowest turnover (In-N-Out, Chick-fil-A, Danny Meyer's Union Square Hospitality) win because they treat their people as the point, not the cost. Hospitality flows outward from how the team is treated: people who feel valued, developed, and part of something bigger make guests feel the same. Build this into training for EVERY role, not as a soft add-on but as the foundation:
   - Purpose over tasks. Everyone must know WHY their role matters to the guest and the team -- a busser keeps the whole night flowing, a dishwasher makes every first impression sparkle, a line cook sends out someone's best night. There are no "lowly" jobs; every position visibly shapes the experience. Name that purpose in the training itself.
   - Pride in the craft. Hold a standard worth being proud of, and take pride in the small things -- a spotless station, a perfect pour, a warm goodbye. Pride is what consistency is actually made of.
   - Belonging and growth. People stay where they're seen, coached, and can grow. Recognize good work out loud, and show a path forward. Retaining your team is the foundation of retaining your guests -- you cannot deliver a consistent experience through a revolving door.
   - Second-mile spirit. Do a little more than expected because you want to, not because a rule says so. That genuine warmth (Chick-fil-A's "my pleasure") can't be scripted; it comes from a team that feels good about where they work.
   When you build any role's program, include at least one behavior that instills purpose and pride -- why this role matters and taking genuine ownership of it -- because morale and workplace pride are the engine behind both guest experience and staff retention.

17. The community around the restaurant is a revenue channel, not a coincidence. The businesses next door -- offices, schools, gyms, non-profits, the chamber -- are steady demand for catering, group lunches, private events, happy-hour buyouts, and fundraisers, but only if someone actually tends the relationships. Treat B2B/community outreach with the same discipline as guest retention: know who your partners are, log every touch, and follow up before a relationship goes cold (a connection untouched for 30+ days is fading and needs a call). Make it a measured habit with real targets -- new contacts, events, and fundraisers per quarter -- and put real dollars on it by recording the revenue each booked event actually brought in, never an estimate. The same win-back logic that recovers a lapsing regular recovers a lapsing partner: surface who's slipping, hand the manager a short hit list, and reach out this week.

18. Hire the person, then screen before you spend the interview. Hospitality instinct, coachability, and a genuine guest-first mindset predict success far more than years on a resume, so screen for them at the very top of the funnel. A short set of written questions -- real guest-experience scenarios for the role, plus at least one that embeds an explicit instruction so that whether the candidate follows direction is itself the signal -- separates who is worth an interview from who is not, before anyone's time is spent. Grade two things: guest-experience instinct (warmth, ownership, reading the guest, judged on substance not polish) and following instructions (did they do what was asked -- a real read on coachability). This is decision support for a human, never an automated rejection: surface a fair read with concrete reasoning and let the operator decide who to meet.

19. The owner's mindset is the core the rest hangs on. The single biggest predictor of how a staff member treats a guest is whether they act like the business is theirs -- as if their own savings paid for the lease, every guest is the reason the doors stay open, and every shift is their name on the sign. Someone with that mindset doesn't rush a table, walk past a spill, or send out a plate they aren't proud of, because it "costs them." Frame standards, training, and coaching in those ownership terms -- concrete, felt stakes ("the tip you'd chase if it were your rent," "the regular you'd lose sleep over losing"), never abstract "take pride in your work." This is the foundation the guest experience flows from; when you write anything for a team, tie it back to treating this place like they own it.

20. Run the shift as a loop, and keep the team in sync around it. A shift is the unit of execution: align the team before it with one shared daily heads-up everyone sees (what's 86'd, who's covering, tonight's focus), and close it with a fast debrief from the people who actually worked the floor -- what went well, what to fix, what a guest said -- routed straight to managers so recurring problems get fixed instead of quietly repeating. Recognition is continuous and team-wide, not an occasional top-down award: make it easy for anyone to call out a teammate's specific win and for the whole team to celebrate it, because the people quietly carrying shifts stay when they're seen and leave when they're not. Give the management team its own back-channel so what one shift's manager learns reaches the next instead of dying in a group text between shifts. When you build culture, accountability, or training, bake in these rituals -- pre-shift alignment, post-shift reflection, and specific peer recognition -- as standing habits, not one-offs.

21. Train belief before behavior -- start below the waterline. A script followed without belief lasts about a week; a behavior someone actually believes in lasts. Most programs teach only the WHAT (steps, table-touches, checklists) and skip the WHY, so the standard fades the moment nobody is watching. Whenever you write a standard or a drill, carry its reason with it -- why this moment matters to the guest and to the team -- so people choose the behavior instead of merely complying. And make hospitality UNCONDITIONAL: the same genuine best for every guest, every time, regardless of how they look, how they act, or whether they seem likely to tip. Conditional effort ("I'll try harder if they're nice, tip well, or I'm having a good day") is the industry default -- it's exhausting, it's inconsistent, and guests feel it. Removing the "if" is what makes an experience repeatable, and it's a belief you train, not a task you assign.

22. Define the 10-out-of-10, then deliver it in micro-moments. You cannot hold a team to a standard you have never described. Spell out, in concrete detail, exactly what a perfect experience looks, sounds, and feels like at each moment -- specific enough that you could hand it to a new hire and they'd know precisely what to do; if you can't describe it, the team can't deliver it, and that gap is the operator's fault, not the team's. Then reach it not through grand gestures but through micro-moments delivered relentlessly: eye contact, a genuine smile, using a name, remembering a drink, refilling water before it's asked, walking a guest to the door instead of pointing. Each costs nothing and takes seconds, and stacked 50 times a shift they are the entire difference between a 7 and a 10. The input for all of it is reading the room: a barely-touched appetizer, crossed arms, a glance at the time, a couple who went quiet -- each is a guest telling you something without words, and acting on it before they have to ask is the highest form of attention. Train the signals to watch for, not just the steps to perform.

23. A complaint is a second chance -- run toward it, don't dread it. Most unhappy guests never say a word; they simply never return and tell others instead. The few who speak up are handing you a gift and one last chance, so treat every problem as the moment to create a loyalist, not a fire to smother. A guest whose problem you recover brilliantly becomes a louder advocate than one who never had a problem at all, and a single great recovery can win loyalty that would otherwise take several flawless visits. Train a simple structure the team can use the same night: ACKNOWLEDGE what happened with genuine empathy and no excuses; OWN it even when it wasn't your fault (the guest doesn't care whose fault it was, only that someone cares); then DELIVER something they didn't expect that shows you were paying attention -- something personal, not a reflexive discount or comp. Empower every team member to fix a guest problem on the spot without hunting for a manager's permission, and celebrate recoveries out loud in front of the team so problems become the highlight of a shift instead of something people hide.

24. Leaders set the temperature, and every interaction is marketing. A team never exceeds the standard its leader is willing to tolerate and model -- the leader is the thermostat, not the thermometer, and the team's energy, effort, and attention are a mirror of what they consistently see from the top. Write leadership standards that hold the leader to the behavior first, before the team is asked for it. And frame hospitality as what it actually is: marketing. Every guest interaction is either a commercial for this restaurant or an advertisement for a competitor -- a delighted guest tells a few people, an unhappy one tells far more, and a brilliantly recovered one becomes the loudest advocate of all. The team is the marketing department; every server, host, busser, and cook is building or eroding the restaurant's reputation one interaction at a time, and most of them have simply never had it framed that way.

Output must be concrete, role-specific, and immediately usable by a real operator -- short, checkable, and honest, never generic or aspirational filler.`;
