import type { Metadata } from "next";
import Link from "next/link";
import { MarketingNav } from "@/components/marketing/nav";
import { MarketingFooter } from "@/components/marketing/footer";
import { InlineCta } from "@/components/marketing/inline-cta";

export const metadata: Metadata = {
  title: "Guest Journey Mapping | Wingman",
  description:
    "Map your restaurant's guest experience moment by moment — from arrival to the ask. Each stage sets the standard, an example script, and what a manager inspects. Generated by AI for your concept.",
  keywords: [
    "restaurant guest journey",
    "guest experience mapping",
    "hospitality touchpoints",
    "restaurant service standards",
    "guest experience training",
  ],
  alternates: { canonical: "/guest-journey" },
  openGraph: {
    title: "Guest Journey Mapping | Wingman",
    description: "Your guest experience, mapped moment by moment — standard, script, and what to inspect at every stage.",
    url: "/guest-journey",
    type: "website",
  },
};

const STAGES = [
  { n: "Arrival", d: "The first seconds set the emotional temperature for the whole visit." },
  { n: "The Greet", d: "One question — new or returning? — changes everything that follows." },
  { n: "Recommendations", d: "Name it, say why it's worth it, give a reason to choose it now." },
  { n: "The Check-back", d: "Close the loop on what you recommended — to each guest, not the table." },
  { n: "The Goodbye", d: "The last moment is the one they remember and repeat." },
  { n: "The Ask", d: "Earn the review, then ask for it — at the natural end of the visit." },
];

const PARTS = [
  { t: "The standard", d: "The non-negotiable, observable behavior for the moment — with a number or trigger where it fits." },
  { t: "An example script", d: "What a team member could actually say or do, written in your restaurant's voice." },
  { t: "What to inspect", d: "The one yes/no thing a manager watches for, so the standard actually gets held — shift to shift." },
];

// Original "journey line" graphic: six stages connected along a path, ending in
// the brand paper-airplane. Pure inline SVG (self-contained, no external assets).
const GRAPHIC_STAGES = ["Arrival", "The Greet", "Recommend", "Check-back", "Goodbye", "The Ask"];

function JourneyGraphic() {
  const n = GRAPHIC_STAGES.length;
  const x0 = 70;
  const x1 = 890;
  const step = (x1 - x0) / (n - 1);
  const y = 78;
  const xs = GRAPHIC_STAGES.map((_, i) => x0 + i * step);
  // A gentle wave through the node centers.
  const path = xs
    .map((x, i) => {
      const yy = y + (i % 2 === 0 ? -14 : 14);
      if (i === 0) return `M ${x} ${yy}`;
      const px = xs[i - 1];
      const py = y + ((i - 1) % 2 === 0 ? -14 : 14);
      const cx = (px + x) / 2;
      return `C ${cx} ${py}, ${cx} ${yy}, ${x} ${yy}`;
    })
    .join(" ");

  return (
    <svg viewBox="0 0 960 170" className="w-full h-auto" role="img" aria-label="A six-stage guest journey from Arrival to The Ask">
      <defs>
        <linearGradient id="gj-line" x1="0" y1="0" x2="1" y2="0">
          <stop offset="0" stopColor="#e9b7b0" />
          <stop offset="1" stopColor="#c0392b" />
        </linearGradient>
      </defs>
      <path d={path} fill="none" stroke="url(#gj-line)" strokeWidth="3" strokeLinecap="round" strokeDasharray="1 10" opacity="0.6" />
      {GRAPHIC_STAGES.map((label, i) => {
        const x = xs[i];
        const yy = y + (i % 2 === 0 ? -14 : 14);
        const last = i === n - 1;
        return (
          <g key={label}>
            <circle cx={x} cy={yy} r="20" fill={last ? "#c0392b" : "#ffffff"} stroke="#c0392b" strokeWidth="2.5" />
            <text x={x} y={yy + 5} textAnchor="middle" fontSize="15" fontWeight="700" fill={last ? "#ffffff" : "#c0392b"}>
              {i + 1}
            </text>
            <text x={x} y={yy > y ? yy + 40 : yy - 30} textAnchor="middle" fontSize="13.5" fontWeight="600" fill="#1a1a1a">
              {label}
            </text>
          </g>
        );
      })}
      {/* The Wingman paper-airplane at the finish (from the logo mark). */}
      <g fill="#0a6cff" transform={`translate(${x1 + 32}, ${y - 6}) scale(0.34) translate(-520, -767)`}>
        <path d="M 573.839844 868.464844 L 553.496094 845.175781 C 553.113281 844.792969 552.449219 844.699219 552.070312 845.175781 L 546.460938 850.785156 C 545.222656 852.019531 543.132812 850.972656 543.039062 849.261719 L 545.605469 837.761719 L 545.890625 837.476562 L 547.316406 836.144531 L 568.324219 814.566406 C 569.085938 813.804688 568.132812 812.472656 567.183594 813.136719 L 539.617188 830.25 C 539.234375 830.441406 538.855469 830.441406 538.476562 830.15625 L 522.3125 816.941406 C 519.558594 814.183594 520.128906 809.714844 523.457031 808.289062 L 615.378906 767.984375 C 619.847656 765.988281 624.792969 770.929688 622.890625 775.492188 L 582.585938 867.324219 C 581.0625 870.652344 576.59375 871.222656 573.839844 868.464844 Z M 573.839844 868.464844 " />
      </g>
    </svg>
  );
}

export default function GuestJourneyPage() {
  return (
    <div className="flex-1 flex flex-col force-light bg-panel">
      <MarketingNav />

      {/* Hero */}
      <section className="max-w-[1180px] mx-auto px-6 sm:px-10 pt-20 sm:pt-28 pb-14 sm:pb-20 text-center">
        <div className="inline-flex items-center gap-2 px-3.5 py-1.5 rounded-full bg-brick-tint mb-7">
          <span className="text-[13px] font-semibold text-brick">Guest Journey Mapping</span>
        </div>
        <h1 className="text-[40px] sm:text-[58px] font-bold tracking-[-0.03em] leading-[1.05] text-ink max-w-[800px] mx-auto">
          Your guest experience, mapped moment by moment
        </h1>
        <p className="text-[18px] sm:text-[20px] text-muted leading-relaxed max-w-[620px] mx-auto mt-6">
          Great hospitality isn&rsquo;t luck — it&rsquo;s a sequence of designed moments. Wingman maps your guest experience from
          arrival to the ask, and gives every stage a standard your team can hit on repeat.
        </p>
        <div className="flex items-center justify-center gap-3 mt-9 flex-wrap">
          <Link href="/demo" className="text-[16px] font-semibold text-white bg-brick rounded-full px-7 py-3.5 hover:bg-brick-dark transition-colors">
            Try the live demo
          </Link>
          <Link href="/signup" className="text-[16px] font-semibold text-ink bg-white border border-line rounded-full px-7 py-3.5 hover:border-brick transition-colors">
            Get Started
          </Link>
        </div>
      </section>

      {/* Journey line graphic */}
      <section className="max-w-[1080px] mx-auto px-6 sm:px-10 w-full pb-6 sm:pb-10">
        <div className="bg-white border border-line rounded-[28px] px-6 sm:px-12 py-10 sm:py-14 shadow-sm overflow-x-auto">
          <JourneyGraphic />
        </div>
      </section>

      {/* The problem */}
      <section className="max-w-[900px] mx-auto px-6 sm:px-10 py-10 sm:py-14 text-center">
        <p className="text-[19px] sm:text-[22px] text-ink leading-relaxed font-medium">
          Most restaurants train a pile of disconnected rules. The best ones train the <span className="text-brick">journey</span> —
          every moment a guest actually experiences, in order, with a clear standard for each. That&rsquo;s what turns a good night
          into a repeatable one.
        </p>
      </section>

      {/* The stages */}
      <section className="max-w-[1180px] mx-auto px-6 sm:px-10 py-10 sm:py-14 w-full">
        <div className="text-center mb-10">
          <h2 className="text-[28px] sm:text-[36px] font-bold tracking-[-0.02em] text-ink">Every moment, on purpose</h2>
          <p className="text-[16px] text-muted mt-3 max-w-[560px] mx-auto">
            Wingman builds the stages that fit your concept — a bar&rsquo;s journey looks different from fine dining. A few of the
            moments it maps:
          </p>
        </div>
        <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-4">
          {STAGES.map((s, i) => (
            <div key={s.n} className="bg-white border border-line rounded-2xl p-6">
              <div className="flex items-center gap-2.5 mb-2">
                <span className="w-7 h-7 rounded-full bg-brick-tint text-brick flex items-center justify-center text-[13px] font-bold">{i + 1}</span>
                <span className="text-[17px] font-semibold text-ink">{s.n}</span>
              </div>
              <p className="text-[14.5px] text-muted leading-relaxed">{s.d}</p>
            </div>
          ))}
        </div>
      </section>

      {/* What each stage holds */}
      <section className="max-w-[1180px] mx-auto px-6 sm:px-10 py-10 sm:py-14 w-full">
        <div className="text-center mb-10">
          <h2 className="text-[28px] sm:text-[36px] font-bold tracking-[-0.02em] text-ink">Not just what — how, and how you hold it</h2>
          <p className="text-[16px] text-muted mt-3 max-w-[560px] mx-auto">Every stage comes with three things that make it real on the floor:</p>
        </div>
        <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
          {PARTS.map((p) => (
            <div key={p.t} className="bg-white border border-line rounded-2xl p-6">
              <div className="text-[17px] font-semibold text-ink mb-2">{p.t}</div>
              <p className="text-[14.5px] text-muted leading-relaxed">{p.d}</p>
            </div>
          ))}
        </div>
      </section>

      {/* AI */}
      <section className="max-w-[900px] mx-auto px-6 sm:px-10 py-10 sm:py-14 text-center">
        <h2 className="text-[28px] sm:text-[36px] font-bold tracking-[-0.02em] text-ink">Generated for your concept in seconds</h2>
        <p className="text-[16px] sm:text-[17px] text-muted leading-relaxed max-w-[560px] mx-auto mt-4">
          Tell Wingman your service style and it drafts a complete journey in your restaurant&rsquo;s voice — then you edit any
          stage to make it yours. From there it becomes the backbone your team trains on and gets spot-checked against.
        </p>
      </section>

      <InlineCta headline="See the guest journey built live" sub="Try the demo, or start your own in minutes." spacingClassName="py-10 sm:py-16" />

      <MarketingFooter />
    </div>
  );
}
