-- ONE-TIME baseline for an existing database.
-- Marks every migration already applied (by hand) as done, so the CI migrator
-- (scripts/apply-migrations.sh) skips them and only runs NEW migrations going
-- forward. Safe to run more than once. Run this once in the Supabase SQL editor.

create table if not exists public.schema_migrations_applied (
  filename text primary key,
  applied_at timestamptz not null default now()
);

-- Internal ops bookkeeping. Enable RLS with NO policies so it's inaccessible via
-- the API (anon/authenticated). The migrator connects as the DB owner and
-- bypasses RLS, so it still reads/writes normally.
alter table public.schema_migrations_applied enable row level security;

insert into public.schema_migrations_applied (filename) values
  ('0001_init.sql'),
  ('0002_role_model_v2.sql'),
  ('0003_reactions_referrals.sql'),
  ('0004_menu_items.sql'),
  ('0005_coaching_preshift_ambiance.sql'),
  ('0006_report_schedules.sql'),
  ('0007_report_schedule_last_sent.sql'),
  ('0008_platform_admin.sql'),
  ('0009_platform_settings.sql'),
  ('0010_growth_plans.sql'),
  ('0011_growth_plan_entries.sql'),
  ('0012_location_contact_fields.sql'),
  ('0013_permission_overrides.sql'),
  ('0014_department_items_source.sql'),
  ('0015_staff_roster.sql'),
  ('0016_hiring_traits_source.sql'),
  ('0017_accountability_checklist_items.sql'),
  ('0018_chef_menu_upload.sql'),
  ('0019_free_org_creation.sql'),
  ('0020_server_upsell_training.sql'),
  ('0021_audits.sql'),
  ('0022_growth_ltv.sql'),
  ('0023_menu_engineering.sql'),
  ('0024_culture_xfactor.sql'),
  ('0025_multi_location_access.sql'),
  ('0026_lock_profile_privilege_columns.sql'),
  ('0027_assign_team_member_org_guard.sql'),
  ('0028_billing_state.sql'),
  ('0029_api_keys.sql'),
  ('0030_rate_limits.sql'),
  ('0031_business_health_metrics.sql'),
  ('0032_shift_checklist_completions.sql'),
  ('0033_playbook_articles.sql'),
  ('0034_support_tickets.sql'),
  ('0035_platform_access.sql'),
  ('0036_ticket_attachments.sql'),
  ('0037_platform_isolation.sql'),
  ('0038_affiliate_program.sql'),
  ('0039_affiliate_commissions.sql'),
  ('0040_affiliate_payouts.sql'),
  ('0041_org_custom_pricing.sql'),
  ('0042_protect_billing_columns.sql'),
  ('0043_leads.sql'),
  ('0044_demo_org.sql'),
  ('0045_demo_sandboxes.sql'),
  ('0046_crm.sql'),
  ('0047_crm_sequences.sql'),
  ('0048_crm_foundation.sql'),
  ('0049_social_posts.sql'),
  ('0050_social_meta.sql'),
  ('0051_social_linkedin.sql'),
  ('0052_social_format.sql'),
  ('0053_coupons.sql'),
  ('0054_journey_stages.sql'),
  ('0055_sales_training_access.sql'),
  ('0056_sales_commissions.sql'),
  ('0057_commission_claims.sql'),
  ('0058_crm_delete_capability.sql'),
  ('0059_commission_payable_on.sql'),
  ('0060_commission_due_reminder.sql'),
  ('0061_staff_w9.sql'),
  ('0062_guest_capture_source.sql'),
  ('0063_journey_inspections.sql'),
  ('0064_social_content_runway.sql'),
  ('0065_crm_past_clients_stage.sql'),
  ('0066_crm_assigned_rep.sql'),
  ('0067_more_departments.sql'),
  ('0068_launch_checkin.sql'),
  ('0069_momentum_nudge.sql'),
  ('0070_weekly_commitments.sql'),
  ('0071_staff_profile_link.sql'),
  ('0072_error_events.sql'),
  ('0073_api_key_location.sql'),
  ('0074_feature_ideas.sql'),
  ('0075_training_signoff_location.sql'),
  ('0076_guest_visit_bill_total.sql'),
  ('0077_tests.sql'),
  ('0078_test_assignments.sql'),
  ('0079_shift_lead_enum.sql'),
  ('0080_shift_lead_rls.sql'),
  ('0081_profile_language.sql'),
  ('0082_content_translations.sql'),
  ('0083_loyalty_checklist.sql'),
  ('0084_job_applications.sql'),
  ('0085_applications_cc.sql'),
  ('0086_test_source_department.sql'),
  ('0087_application_interviews.sql'),
  ('0088_platform_pricing.sql'),
  ('0089_test_reminder_alerted.sql'),
  ('0090_org_notification_settings.sql'),
  ('0091_application_form_config.sql') on conflict (filename) do nothing;
